// NEW: Reports Center config
export const reportsConfig = [
  {
    id: "dailySales",
    title: "Daily Sales Summary",
    description: "Sales, covers, and average check by outlet and date.",
    category: "Sales",
    tags: ["daily", "sales", "outlet"],
    icon: "bar_chart",
    route: "/api/reports/sales-summary",
    defaultDateRange: "last7Days",
    requiredFilters: ["dateRange", "outlet"],
  },
  {
    id: "laborCost",
    title: "Labor Cost % of Sales",
    description: "Labor cost vs net sales by outlet and period.",
    category: "Labor",
    tags: ["labor", "kpi", "cost"],
    route: "/api/reports/hr-summary",
    defaultDateRange: "last30Days",
    requiredFilters: ["dateRange", "outlet"],
  },
  {
    id: "wasteVariance",
    title: "Waste & Variance",
    description: "Waste cost and quantities by category/reason.",
    category: "Operations",
    tags: ["waste", "variance"],
    route: "/api/reports/waste-summary",
    defaultDateRange: "last30Days",
    requiredFilters: ["dateRange", "brand"],
  },
  {
    id: "purchases",
    title: "Purchases / COGS",
    description: "Total purchase cost by supplier/category.",
    category: "Purchases",
    tags: ["cogs", "purchases"],
    route: "/api/reports/purchases-summary",
    defaultDateRange: "last30Days",
    requiredFilters: ["dateRange", "supplier"],
  },
  {
    id: "rentOpex",
    title: "Rent & Opex",
    description: "Operating expenses by outlet and category.",
    category: "Finance",
    tags: ["opex", "rent"],
    route: "/api/reports/rent-opex-summary",
    defaultDateRange: "last30Days",
    requiredFilters: ["dateRange", "outlet"],
  },
  {
    id: "pettyCash",
    title: "Petty Cash",
    description: "Petty cash spend by category and outlet.",
    category: "Finance",
    tags: ["petty", "cash"],
    route: "/api/reports/petty-cash-summary",
    defaultDateRange: "last30Days",
    requiredFilters: ["dateRange", "outlet"],
  },
  {
    id: "inventory",
    title: "Inventory Snapshot",
    description: "Item counts, quantities, and average costs.",
    category: "Inventory",
    tags: ["inventory", "items"],
    route: "/api/reports/inventory-summary",
    defaultDateRange: "all",
    requiredFilters: ["category", "brand"],
  },
];
