// src/features/hr/HrHub.jsx
import { useMemo, useState } from "react";
import { callAi } from "../../utils/aiClient";
import { useData } from "../../DataContext";

function HrHub() {
  const { brandFilter, outletFilter, startDate, endDate } = useData();
  const [roster, setRoster] = useState("");
  const [constraints, setConstraints] = useState(
    "Budget, service hours, roles"
  );
  const [targets, setTargets] = useState({
    laborPct: "30",
    avgCovers: "",
    peakHours: "Fri/Sat 6-10pm",
  });
  const [aiText, setAiText] = useState("");
  const [aiRisks, setAiRisks] = useState("");
  const [aiLoading, setAiLoading] = useState(false);

  const headerNote = useMemo(() => {
    const parts = [];
    if (brandFilter) parts.push(`Brand: ${brandFilter}`);
    if (outletFilter) parts.push(`Outlet: ${outletFilter}`);
    if (startDate || endDate) parts.push(`Dates: ${startDate || "Any"} to ${endDate || "Any"}`);
    return parts.join(" | ");
  }, [brandFilter, outletFilter, startDate, endDate]);

  async function handleAiStaffing() {
    setAiLoading(true);
    setAiText("");
    setAiRisks("");
    try {
      const payload = {
        viewId: "hrStaffing",
        filters: { brandFilter, outletFilter, startDate, endDate },
        roster,
        constraints,
        targets,
      };

      const question =
        "Return markdown with two sections: ## Staffing Plan (roles/headcount/shifts by outlet) and ## Risks & Actions (over/under staffing, cross-training, scheduling tweaks). Respect target labor %, peak hours, and budget.";

      const res = await callAi({ mode: "report", payload, question });
      const txt = res.text || "";
      setAiText(txt);
      setAiRisks("Generated by " + (res.model || "AI model"));
    } catch (err) {
      setAiText(`AI staffing failed: ${err.message || "Unknown error"}`);
    } finally {
      setAiLoading(false);
    }
  }

  return (
    <div>
      <h2 className="page-title">HR & Staffing</h2>
      <p className="page-subtitle">
        Assess staffing by brand/outlet and get AI recommendations for headcount,
        shifts, and role mix.
      </p>

      <div className="card" style={{ display: "grid", gap: 12 }}>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
          <div>
            <label className="field-label">Target labor %</label>
            <input
              type="number"
              step="0.1"
              value={targets.laborPct}
              onChange={(e) =>
                setTargets((t) => ({ ...t, laborPct: e.target.value }))
              }
              style={{ width: 120 }}
            />
          </div>
          <div>
            <label className="field-label">Avg covers / day</label>
            <input
              type="number"
              step="1"
              value={targets.avgCovers}
              onChange={(e) =>
                setTargets((t) => ({ ...t, avgCovers: e.target.value }))
              }
              placeholder="e.g. 200"
              style={{ width: 140 }}
            />
          </div>
          <div style={{ flex: 1, minWidth: 200 }}>
            <label className="field-label">Peak hours / notes</label>
            <input
              type="text"
              value={targets.peakHours}
              onChange={(e) =>
                setTargets((t) => ({ ...t, peakHours: e.target.value }))
              }
              placeholder="Fri/Sat 6-10pm; weekday lunch 12-2"
            />
          </div>
        </div>

        <div>
          <label className="field-label">
            Roster snapshot (paste employees, role, outlet, hours)
          </label>
          <textarea
            rows={5}
            value={roster}
            onChange={(e) => setRoster(e.target.value)}
            placeholder="e.g. Ali / FOH / Outlet A / 40h; Sara / BOH / Outlet B / 30h; ..."
          />
        </div>

        <div>
          <label className="field-label">Constraints / goals</label>
          <input
            type="text"
            value={constraints}
            onChange={(e) => setConstraints(e.target.value)}
            placeholder="Budget per outlet, target labor %, service hours, roles needed"
          />
        </div>

        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <button
            type="button"
            className="primary-btn"
            onClick={handleAiStaffing}
            disabled={aiLoading}
          >
            {aiLoading ? "Thinking..." : "Get AI staffing plan"}
          </button>
          <span className="hint-text">
            Filters applied: {brandFilter || "All brands"} / {outletFilter || "All outlets"}
          </span>
        </div>

        {aiText && (
          <div
            className="ai-output-box"
            style={{
              marginTop: 8,
              background: "#f8fafc",
              padding: 10,
              borderRadius: 8,
              border: "1px solid #e5e7eb",
              whiteSpace: "pre-wrap",
              fontSize: 13,
            }}
          >
            {aiText}
            {aiRisks && (
              <div style={{ marginTop: 6, fontSize: 11, color: "#475569" }}>
                {aiRisks}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default HrHub;
